### ISSUE TITLE
URL generation of related posts not working

### ISSUE THREAD

**Issue by tsphethean** [tsphethean/sculpin-related-posts-bundle#1]
Currently, the URL returned for each related post is empty, or the path to the source rather than its output. 

Need to figure out how to generate the permalink for a related source

**Comment by tsphethean** [comment]
Fixed

**Comment by emcoward** [comment]
Hi Tom,

I just tried to use your related posts bundle and it seems the URL returned for each related post is still empty? Is there an update available for this bundle at all?

**Comment by opdavies** [comment]
Confirmed. `{{ dump(relate.url) }}` is returning `NULL` for each related post.

**Comment by tsphethean** [comment]
Thanks for raising @opdavies and @emcoward - and sorry for a slow reply. I think something has changed in sculpin core since I wrote the related posts bundle, I checked my local site and I was still running version 2.0.x-dev (2be36c3). On upgrading to the latest version I get the same issue as you.

I'll try and debug this over the next couple of days.

**Comment by tsphethean** [comment]
Hm. I'm not sure how my original documentation ever worked... The bundle provides the full source of the related posts, so you can access any of the properties via relate.source.XXXX as in the below:

```
{% for relate in page.related %}
<li><a href="{{ relate.source.url }}">{{ relate.title }}</a></li>
{% endfor %}
```

I've tested this on my site and it is pulling through correctly - please could you test and if confirmed I'll update the template snippet in the readme?

I'll also open a ticket to add some tests :)

**Comment by opdavies** [comment]
`{{ relate.source.url }}` works for me! :)

**Comment by emcoward** [comment]
Thanks Tom, that works for me too :)

**Comment by tsphethean** [comment]
Great, thanks both for testing - I've updated the README now.

**Comment by opdavies** [comment]
@tsphethean What about displaying additional data, such as the date of the related post? Both `{{ related_post.date }}` and `{{ related_post.source.date }}` return NULL.

I'm building a demo Sculpin site (https://github.com/opdavies/sculpin-demo) for future presentations and am including this bundle as an example of using additional bundles, so it would be good to show as much information about the related posts as possible.

**Comment by opdavies** [comment]
Unfortunately, `{{ dump(related_post) }}` and `{{ dump(related_post.source) }}`always result in an "Allocated memory size" error so I can't see what properties are available to use.
